### PR TITLE
Rename the custom device, add document outlining supported hardware and driver requirements

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-chassis-timesync-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Rename the custom device from "Chassis TimeSync Custom Device" to "NI Synchronization Custom Device".

Add a document outlining what the minimum driver requirements are.

### Why should this Pull Request be merged?

The custom device name change comes from the product owners.

The driver requirements are not currently documented anywhere; this adds them to the repo.

### What testing has been done?

Built the custom device and confirmed deployment to both PharLap and Linux.

### CODE REVIEW

**Comment by rtzoeller** [comment]
@buckd  `build.toml` is updated, kicked off [another build](http://coordinator/job/VeriStand/job/ni/job/niveristand-chassis-timesync-custom-device/view/change-requests/job/PR-17/)

**Comment by csjall** [comment]
- [ ] Rename "Timing and Sync Chassis TimeSync.xml" to "NI Synchronization.xml" and update reference in the LabVIEW project file.
- [ ] Rename "Chassis TimeSync Unit Tests.lvclass" to "NI Synchronization Unit Tests.lvclass" and update reference in the LabVIEW project file.
- [ ] Rename the repository once this change is approved and merged.
- [ ] Inform the RTT group once the name has been updated to avoid any surprises. User with the old plugin may have to scrub their custom devices folder.

**Comment by rtzoeller** [comment]
- [ ] Update the custom device to use new GUIDs such that it does not conflict with the old one.

**Comment by rtzoeller** [comment]
@csjall [VeriStand requires the xml file be prefixed with "Timing and Sync"](http://zone.ni.com/reference/en-XX/help/372846L-01/veristandmerge/cust_device_xml/), so I am renaming the XML file to `Timing and Sync - NI Synchronization.xml`.

**Pull request merged**
